version: '3.2'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager

  web:
    image: subjectrefresh/shortener:latest
    deploy:
      mode: replicated
      replicas: 4
    environment:
      NODE_ENV: production
      PORT: 3000
      SSL: 'true'
      URL: subr.pw
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
      - 443:443

volumes:
  mongo-data: