version: '3.2'

services:
  mongo:
    ports:
      - '27018:27017'

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /shortener/node_modules # prevent them being overwritten by the above
      - .:/shortener
    environment:
      NODE_ENV: development
      SSL: 'false'
      URL: localhost
      PORT: 3001
    ports:
      - 3001:3001