version: '3.2'

services:
  mongo:
    ports:
      - '27018:27017'

  web:
    build: .
    volumes:
      - /shortener/node_modules # prevent them being overwritten by the above
      - .:/shortener
    environment:
      NODE_ENV: development
      SSL: 'false'
      URL: localhost
      PORT: 3001
    ports:
      - 3001:3001
    command: ["npm", "run", "dev"]
  
secrets:
  shortener_session_secret:
    file: ./secrets/session_secret