version: '3.2'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager

  web:
    image: subjectrefresh/shortener:latest
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 6
    environment:
      NODE_ENV: production
      PORT: 80
      SSL: 'true'
      URL: subr.pw
    depends_on:
      - mongo

volumes:
  mongo-data: